### ISSUE TITLE
Google API token keeps being revoked

### ISSUE THREAD

**Issue by cmenon12** [cmenon12/contemporary-choir#5]
First occurred at 21:30 on 15/01/2021. Need to preferably stop this happening.

Alternatively, the program could be altered to detect the error and automatically prompt for the user to re-authorise - this would only be useful for when it's run manually. This would involve manually deleting the `token.pickle` file.
 
```
Traceback (most recent call last):
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_checker.py", line 527, in main
    check_ledger(save_data=save_data, parser=parser)
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_checker.py", line 425, in check_ledger
    sheets_data = ledger.get_sheets_data()
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_fetcher.py", line 475, in get_sheets_data
    self.upload_to_sheets(convert=convert, save=save)
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_fetcher.py", line 276, in upload_to_sheets
    drive, sheets, apps_script = Ledger.authorize(open_browser=False)
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_fetcher.py", line 660, in authorize
    credentials.refresh(Request())
  File "/home/pi/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google/oauth2/credentials.py", line 206, in refresh
    self._scopes,
  File "/home/pi/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google/oauth2/_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/pi/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/pi/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')
```

**Comment by cmenon12** [comment]
No changes to `ledger_fetcher.py` in https://github.com/cmenon12/contemporary-choir/compare/a6e85c2..9bf1bab#diff-1186197450597eadbe2430deb8bc50dc9d4665da65e236f514bc0072337bb40b.

**Comment by cmenon12** [comment]
Attempted a fix with https://github.com/cmenon12/contemporary-choir/commit/8d12879514c5c8e2b7c1b551e7993170f98476d4.
Need to wait ~10 days to see if the issue re-occurs after this commit.

**Comment by cmenon12** [comment]
The fix (https://github.com/cmenon12/contemporary-choir/commit/8d12879514c5c8e2b7c1b551e7993170f98476d4) didn't work.
```
ERROR ON MONDAY 29 MARCH 2021 AT 22:00:23
Traceback (most recent call last):
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_checker.py", line 527, in main
    check_ledger(save_data=save_data, parser=parser)
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_checker.py", line 425, in check_ledger
    sheets_data = ledger.get_sheets_data()
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_fetcher.py", line 499, in get_sheets_data
    self.upload_to_sheets(convert=convert, save=save)
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_fetcher.py", line 302, in upload_to_sheets
    drive, sheets, apps_script = Ledger.authorize(open_browser=self.browser_path)
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_fetcher.py", line 711, in authorize
    credentials.refresh(Request())
  File "/home/pi/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google/oauth2/credentials.py", line 206, in refresh
    self._scopes,
  File "/home/pi/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google/oauth2/_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/pi/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/pi/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')
```

**Comment by cmenon12** [comment]
Attempted a fix with https://github.com/cmenon12/contemporary-choir/commit/14a1af47319304b6922756b433704b44592bed3d.
Need to wait ~10 days to see if the issue re-occurs after this commit.

**Comment by cmenon12** [comment]
The fix (https://github.com/cmenon12/contemporary-choir/commit/14a1af47319304b6922756b433704b44592bed3d) didn't work.
```
ERROR ON TUESDAY 06 APRIL 2021 AT 18:30:23
Traceback (most recent call last):
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_checker.py", line 584, in main
    check_ledger(save_data=save_data, parser=parser)
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_checker.py", line 476, in check_ledger
    sheets_data = ledger.get_sheets_data()
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_fetcher.py", line 499, in get_sheets_data
    self.upload_to_sheets(convert=convert, save=save)
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_fetcher.py", line 302, in upload_to_sheets
    drive, sheets, apps_script = Ledger.authorize(open_browser=self.browser_path)
  File "/home/pi/Documents/contemporary-choir/python-scripts/ledger_fetcher.py", line 711, in authorize
    credentials.refresh(Request())
  File "/home/pi/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google/oauth2/credentials.py", line 206, in refresh
    self._scopes,
  File "/home/pi/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google/oauth2/_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/pi/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/pi/.pyenv/versions/3.7.7/lib/python3.7/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.', '{\n  "error": "invalid_grant",\n  "error_description": "Token has been expired or revoked."\n}')
```

**Comment by cmenon12** [comment]
Looks like Google have designed it to expire after 7 days, which is disappointing.

According to [their support docs](https://developers.google.com/identity/protocols/oauth2#expiration):

> A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

A possible solution might therefore be to use a service account that already has access (although this could be subject to the same limits).

**Comment by cmenon12** [comment]
Changed the publishing status from Testing to In Production (without verification), which might fix the issue!

Also added automatic re-authorization if the refresh token is revoked, and a timeout for authorization (https://github.com/cmenon12/contemporary-choir/commit/2fa7592e9cbae5847a36ebc9a3976f90c6d71af4).

**Comment by cmenon12** [comment]
Issue has not reoccurred, closing this.
